### finally connecting elastic data to R.

There is a package built for this purpose that allows retrieving data easily from `elastic` (also the package name) system in to R, and writing queries in R local langauge and working with it. 

> Please make sure that each time the connection between R and elasticsearch database is created, the elastic instance is running on the port `9200` (by default), to do this use: elasticsearch directory, go to command line, make it your current directory, and run `bin/elastic(for OS) or bin/elastic.bat(for windows)` 

```
install.packages("elastic")
library('elastic')
connect(es_port = 9200)
count(index='spainsoccer')
Search(index = "spainsoccer", size=10, id= 10 )$hits$hits  #to get 10 id data for type= liga_data 

#spainsoccer is also the database name, which is used here for automatic indexing within elastic database.

```

we choose 3920, as this the maximum size of our data right now, it could be increased or decreased as per requirements.
we can change that and specify our custom index by using `docs_bulk(spainsoccer, index = "elasticsoccer")`
```
res <- Search(index = "spainsoccer", size=3920, asdf = T) #dataframe
resdf <- res$hits$hits$'_source'
```
